server.port: 8080
spring:
  security:
    user:
      name: root
      password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: vhe
          uri: http://127.0.0.1:15101
          predicates:
          - Path=/vhe/**
          filters:
          - StripPrefix=1
